name: bitcoin
version: 0.0.0
author: Steven Roose <stevenroose@gmail.com>
description: A Bitcoin library for Dart. Pub-test release.
homepage: http://www.dartcoin.org/
dependencies:
  asn1lib: ">=0.3.1"
  base58check: ^1.0.0
  bignum: ">=0.0.4"
  bytes: ">=0.2.0 <0.3.0"
  collection: any
  cryptoutils: ">=0.1.8"
  pointycastle: any
dev_dependencies:
  browser: any
  test: any
  uuid: any
